version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - internal

networks:
  internal:
    external: false
